### ISSUE TITLE
Network Policy blocks UI-Access on kyma

### ISSUE THREAD

**Issue by Roncossek** [SAP-samples/btp-cap-multitenant-saas#52]
In the [Test the application](https://github.com/SAP-samples/btp-cap-multitenant-saas/blob/main/docu/2-basic/6-test-the-application/README.md) section, when trying to access the application UI the load runs into a timeout:

```txt
browser console output:
consumer-1-ussa-sustainable-saas-router-playground.e3c8675.kyma.ondemand.com/:1 
        Failed to load resource: the server responded with a status of 503 ()
GET https://consumer-1-ussa-sustainable-saas-router-playground.e3c8675.kyma.ondemand.com/favicon.ico 503 (Service Unavailable)
```

![image](https://github.com/user-attachments/assets/3951fde9-90dd-49d5-8990-60c8eff9c06e)

When deleting the Network Policy for the router the request is successful. 

```yaml
# deploy/kyma/charts/sustainable-saas/charts/susaas-router/templates/network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "susaas-router.fullname" . }}
  labels: {{- include "susaas-router.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels: {{- include "susaas-router.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: istio-ingressgateway
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: istio-system
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: oathkeeper
            app.kubernetes.io/instance: ory
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: istio-system

```

I did not find a proper solution but found that oathkeeper was deprecated as of kyma 2.2 as mentioned in [Technology Blogs by SAP](https://community.sap.com/t5/technology-blogs-by-sap/sap-btp-kyma-runtime-api-gateway-future-architecture-based-on-istio/ba-p/13567213)
